version: '3'

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    # If on MACOS with M1 chip, you need to change the user just to prevent ID conflicts
    # user: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: lneves07/nginx:prod
    container_name: nginx
    networks:
      - node-net
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: ./node
    image: lneves07/node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - node-net
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db

networks:
  node-net:
    driver: bridge
